### ISSUE TITLE
Recording width, height, fps not available in some codecs but needed

### ISSUE THREAD

**Issue by Linwood-F** [ShinobiCCTV/Shinobi#18]
Scenario: Input type H.264 via RTSP TCP, with recording type MP4 and Codec libx264 (Default), there is no settings for the height, width or fps. 

Looking at the command line of the running ffmpeg shows it using a far smaller wxh and slower frame rate than the camera setting, and the resulting file is the smaller size.

If the record Codec is set to Auto or Default, then the width/height/fps all appear.  Note that libx264 was the default, i.e. it automatically appeared, even though there is a separate menu option "Default".   With the libx264 (Default) these options are missing; with "Default" they are present.

If you change them under Default, save, then go back and change the codec to libx264 (they disappear) and save, they actually remain in effect and can be seen in the ffmpeg command line, and in the resulting file.

Further, even once you change the frame rate (I went from 1 to 4) the popup on the UI which shows the frame rate still shows 1 (but I confirmed by manually looking at the file it is 4).

**Comment by Soljia** [comment]
Hm, i'm seeing the same thing in the proccess. However, I don't see any stretching or side bar going on. Is it maybe ignoring the resolution command?

**Comment by Soljia** [comment]
It has to be ignoring some commands. if you notice, the -r (framerate) is 1. Which is another bug that should recording only at 1 FPS. However, my recordings (and live) are not 1 FPS.

**Comment by Soljia** [comment]
So here is my full command. I'm assuming since -s is listed twice, it is honoring the last one.

`ffmpeg -loglevel warning -rtsp_transport tcp -i rtsp://******************:554/Streaming/Channels/1 -vcodec copy -r 1 -s 640x480 -f segment -segment_atclocktime 1 -reset_timestamps 1 -strftime 1 -segment_list pipe:2 -segment_time 900 /mnt/External/Shinobi/2Df5hBE/EzDTwjZBQA/%Y-%m-%dT%H-%M-%S.mp4 -preset ultrafast -crf 20 -an -c:v copy -r 20 -f hls -s 1280x720 -tune zerolatency -g 1 -hls_time 2 -hls_list_size 3 -start_number 0 -hls_+`

**Comment by moeiscool** [comment]
wow sorry i didn't reply I completely just missed it in my to do list. The GUI is a little screwy in the master version I will be merging the fixes to master soon. If you would like to pickup the changes (and possibly a few new bugs) you can grab the dev branch :)
