### ISSUE TITLE
MPEG-DASH not working

### ISSUE THREAD

**Issue by Bonnee** [ShinobiCCTV/Shinobi#27]
I recently discovered that Shinobi now lists MPEG-DASH as a streaming option, but I didn't manage to make it work. The stream is all black and I get these messages in the web console:
![2017-11-05-150521_1920x1080_scrot](https://user-images.githubusercontent.com/12095774/32415499-eec5a916-c23a-11e7-8cb6-22ca0eecf1be.png)

**Comment by moeiscool** [comment]
hmm, thank you. ill have a look. It's most likely i didn't bind elements correctly.

**Comment by moeiscool** [comment]
Sorry to say I did have MPEG-DASH working. However there wasn't enough of a performance boost in comparison to HLS that made it worth keeping.

This is not to say I simply removed something you may have once had. It is has been replaced with FLV streaming. Shown in the browser with flv.js https://github.com/Bilibili/flv.js/.

So far the results are amazing. The latency is around 0.5 - 2 seconds. Best part is that it uses copy method just like HLS :smile: 

Grab it in the latest dev!.. and with all my jibber jabber this issue comes to a close!

**Comment by kevinGodell** [comment]
Actually, mpeg-dash performed better in the browser(noticeably on mac) when it came to the cpu load because it did not have to mux mpegts segments into mp4 chunks before feeding mse. Now that the latest version of ffmpeg HLS supports -hls_segment_type fmp4, HLS now performs as good in the browser, but can reach one additional browser that mpeg-dash could not.

**Comment by moeiscool** [comment]
for me dash.js wasn't as good as HLS. The delay appeared to be a lot longer. I guess maybe i didn't tune enough. It had about 10 seconds delay while HLS never went above 5 seconds and would normally be around 3 seconds.
