### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by pcassimans** [ShinobiCCTV/Shinobi#31]
There are different licenses declared in the project. Would be good to decide which one the project will live under.
In the LICENSE file it is declared as:
```
Software under licence Creative Commons 4.0 
https://creativecommons.org/licenses/by-nc-sa/4.0/
```

In the package.json file:
```
  "license": "GPLv3",
```

If GPLv3, please adapt it in the package.json file to 
```
  "license": "GPL-3.0",
```
to be SPDX compliant, which again will take a warning away in the compile.

**Comment by moeiscool** [comment]
Thanks! Ill modify the package.json. The project lives under two licenses because there are two versions of Shinobi. One is CC4 (Pro) and one is GPLv3 (CE).

The only difference is the license. Since you mentioned this you are probably aware of the limitations when it comes to commercializing a project under GPLv3. This is why there are two repos. One allows me to monetize my work while the other allows freedom in it's use, leaving the choice of giving something back or not.

There are no license enforcement mechanisms in Shinobi so I do a direct copy (excluding the license file and readme) every now and then. Shinobi CE ets updated less often but the code base is the same.
