### ISSUE TITLE
m3u8 list are accesible without authentication

### ISSUE THREAD

**Issue by franco87** [ShinobiCCTV/Shinobi#36]
When I take the s.m3u8 link from Monitors, It is available even after logout.
User auth token is still valid after logout

Stream Type: HLS
Video Encoder: Copy

Shinobi version: up to date with master branch

**Comment by moeiscool** [comment]
:sweat_smile: i fix one thing and cause another problem. Originally the session key didn't work if you weren't logged in on the websocket server. I have since changed that. You can use whatever session key is in the field as your API key.

I guess the fix for this would be to empty the session key in the db when the user chooses to logout.

**Comment by franco87** [comment]
I think the problem is that token is keep in memory after logout. Only after a while, just when `clearAfterTime` is executed, the token becomes invalid.

I can not see a "logout" function on the server side. So you must manage this, I think. 
The security on this kind of software is critical

**Comment by moeiscool** [comment]
yah, i need to make a handler. The logout stuff currently only happens in client side. This was ok when the session key was not usable as an API until logged into the websocket.

`clearAfterTime` activates if a session key is used but you are not logged in to the websocket engine.

yes, i'm aware security is critical :sweat_smile: *cough* security platform *cough* :smile: Thanks for mentioning! i'll fix it as soon as i can.

**Comment by moeiscool** [comment]
fixed and will be in master in the next merge from dev. https://github.com/ShinobiCCTV/Shinobi/commit/d88a0d62295463cb895d3e180b1ed2723a4adb40
